Merged v2.1 into default. Clobbering previous contents.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,252 +1,311 @@
 #!/bin/bash
-
-## Ensure exit on error:
-# set -e
-
-
-
-
-## Begin logging in config.log
-LOG_FILE=config.log
-date | tee $LOG_FILE
-
-## Define some defaults which are modified by the script and whatever
-## is defined in configure.deps
-RELEASE_DIR=release
-DEBUG_DIR=debug
-PROFILE_DIR=profile
-INSTALL_DIR=/usr/local
-EXPERIMENTAL=false
-GRAPHLAB_HOME=$PWD
-
-
-## Overwrite defaults if they are available
-if [ -f configure.deps ]; then
-  source configure.deps
-fi
-
-
-
-
+##=============================================================================
+## Support code
+function download_file {
+  # detect wget
+  echo "Downloading $2 from $1 ..."
+  if [ -z `which wget` ] ; then
+    if [ -z `which curl` ] ; then
+      echo "Unable to find either curl or wget! Cannot proceed with 
+            automatic install."
+      exit 1
+    fi
+    curl $1 -o $2
+  else
+    wget $1 -O $2
+  fi
+} # end of download file
 function print_help {
-  echo "Usage: ./configure [--bootstrap] [--force_cmake_install]"
-  echo "                   [--force_boost_install] [--prefix=PREFIX]"
-  echo "                   [--experimental]"
+  echo "Usage: ./configure [--prefix=PREFIX] [--experimental]"
   echo
-  echo "      --cleanup               remove all build directories"
+  echo "  --cleanup           remove all build directories"
   echo 
-  echo "      --bootstrap             bootstrap will install CMake/Boost if they are not detected."
+  echo "  --prefix=[PREFIX]   GraphLab Installation target directory. Defaults to /usr/local"
   echo
-  echo "      --yes                   automatically install dependencies locally if they are not met."
+  echo "  --ide=[Xcode]       Specify the ide to use when building GraphLab."
   echo
-  echo "      --force_cmake_install   This forces a CMake installation even if CMake is detected."
+  echo "  --no_openmp         Disables OpenMP. Disabled by default on Mac."
   echo
-  echo "      --force_boost_install   This forces a Boost installation even if Boost is detected."
-  echo
-  echo "      --prefix=[PREFIX]       GraphLab Installation target directory. Defaults to /usr/local"
+  echo "  --no_jvm             Disable JVM features including HDFS integration."
   echo 
-  echo "      --experimental          Turns on undocumented experimental distributed capabilities. "
-  echo 
-  echo "      --itpp                  Try to automatically build itpp"
+  echo "  --experimental      Turns on undocumented experimental capabilities. "
   echo
-  echo "      --itpp_include_dir=[DIR] specify manually itpp include directories (path to itpp header files)."
-  echo 
-  echo "      --itpp_static_link_dir=[DIR]   specify manually static itpp link dir (path to libitpp.a lib)."
-  echo
-  echo "      --itpp_dynamic_link_dir=[DIR]   specify manually dynamic itpp link dir (path to libitpp.so lib)."
-  echo
-  echo "      --itpp_lapack_dir=[DIR]   specify manually lapack dir (path to liblapack.so lib)."
-  echo
-   echo "      --eigen                 Install Eigen linear algebra package "
-  echo
-  echo "      -D something=something  specify definitions to be passed on to cmake."
-  echo
+  echo "  -D var=value        Specify definitions to be passed on to cmake."
+ 
   exit 1
-}
-
+} # end of print help
 function run_cleanup {
   #!/bin/bash
   echo "This script completely erases all build folders including dependencies!!!"
   echo "Are you sure you want to continue? (yes or no)"
   read yesorno;
   if [ "$yesorno" == "yes" ]; then 
-    echo "Removing release debug and profile folders";
-    rm -rf release debug profile deps configure.deps
+    echo "Removing release and debug folders";
+    rm -rf release debug deps configure.deps
   else
     echo "Doing nothing!";
   fi 
   exit 1
-}
-
-
+} # end of run cleanup
 function unknown_option {
   echo "Unrecognized option: $1"
   echo "To get help, run ./configure --help"
   exit 1
-}
+} # end of unknown option
+function check_version {
+  local version=$1 check=$2
+  local winner=$(echo -e "$version\n$check" | sed '/^$/d' | sort -nr | head -1)
+  [[ "$winner" = "$version" ]] && return 0
+  return 1
+} # end of check version
 
-config_flags=""
 
+
+##=============================================================================
+## Main configuration processing
+
+## Define some defaults which are modified by the script and whatever
+## is defined in configure.deps
+RELEASE_DIR=release
+DEBUG_DIR=debug
+INSTALL_DIR=/usr/local
+EXPERIMENTAL=false
+GRAPHLAB_HOME=$PWD
+DEPS_PREFIX=$PWD/deps/local
+NO_OPENMP=false
+CFLAGS="" 
+
+# if mac detected, force no_openmp flags by default
+if [[ $OSTYPE == darwin* ]]; then
+  NO_OPENMP=true
+fi
+
+
+## The defaults can be overwritten be editing the configure.deps file
+if [ -f configure.deps ]; then
+#  source configure.deps
+  # We delete the configure deps and then recreate it each time using
+  # the original values along with any modifications made by the
+  # configure logic.
+  rm configure.deps
+fi
+
+
+# Parse command line configure flags ------------------------------------------
 while [ $# -gt 0 ]
   do case $1 in
-    --help)                 print_help ;;
-    --cleanup)              run_cleanup ;;
-    --bootstrap)            bootstrap=1 ;;
-    --yes)                  always_yes=1;;
-    --force_cmake_install)  force_cmake_install=1 ;;
-    --force_boost_install)  force_boost_install=1 ;;
-    --prefix=*)             prefix=${1##--prefix=} ;;
+    --help)                 print_help=1 ;;
+    --cleanup)              run_cleanup=1 ;;
+    --no_openmp)            no_openmp=1 ;;
+    --no_jvm)               no_jvm=1 ;;
     --experimental)         experimental=1 ;;
-    --itpp)                 itpp=1 ;;
-    --itpp_include_dir=*)   itpp_include_dir=${1##--itpp_include_dir=} ;;
-    --itpp_static_link_dir=*)       itpp_static_link_dir=${1##--itpp_static_link_dir=} ;;
-    --itpp_dynamic_link_dir=*)      itpp_dynamic_link_dir=${1##--itpp_dynamic_link_dir=} ;;
-    --itpp_lapack_dir=*)    itpp_lapack_dir=${1##--itpp_lapack_dir=} ;;
-    --eigen)		    install_eigen=1 ;;
- #   --yrlabs)               yrlabs=1 ;; # Yahoo Research Experimental Components
-    -D)                      config_flags="$config_flags -D $2"; shift ;;
+    --prefix=*)             prefix=${1##--prefix=} ;;
+    --ide=*)                ide=${1##--ide=} ;;
+    -D)                     CFLAGS="$CFLAGS -D $2"; shift ;;
     *) unknown_option $1 ;;
   esac
   shift
 done
 
-##==========================================================
-##  Construct configure.deps file specifying the necessary environment
-##  variables
-
-# Create a configure deps if no such file already exists
-if [ ! -f configure.deps ]; then
-  # Initialize with default settings
-  echo "RELEASE_DIR=$RELEASE_DIR"     >> configure.deps
-  echo "DEBUG_DIR=$DEBUG_DIR"         >> configure.deps
-  echo "PROFILE_DIR=$PROFILE_DIR"     >> configure.deps
-fi
-
-# Enable or disable experimental graphlab components
-if [ ! -z $experimental ]; then
-  echo "EXPERIMENTAL=true"       >> configure.deps
-else
-  echo "EXPERIMENTAL=$EXPERIMENTAL"      >> configure.deps
-fi
-
-# # Enable or disable Yahoo Research Labs Experimental components
-# if [ ! -z $yrlabs ]; then
-#   echo "YRL_EXPERIMENTAL=true"       >> configure.deps
-# else
-#   echo "YRL_EXPERIMENTAL=$YRL_EXPERIMENTAL"      >> configure.deps
-# fi
-
-
-# Run the configure deps
-source configure.deps 
-
-
-# Run the bootstrap script which populates configure.deps
-if [ ! -z $bootstrap ]; then
-  source ./scripts/bootstrap.sh | tee -a $LOG_FILE
-fi
-
-if [ ! -z $install_eigen ]; then
-  source ./scripts/eigen_install.sh `pwd` | tee -a $LOG_FILE
-  echo "Eigen setup OK"
-  HAS_EIGEN=1;
-# Try to build itpp
-elif [ ! -z $itpp ]; then
-  source ./scripts/itpp_install.sh | tee -a $LOG_FILE
+if [ $print_help ]; then
+  print_help;
 fi
 
 
-#if the prefix is not specified
-if [ ! -z $prefix ]; then
-  echo "INSTALL_DIR=$prefix"     >> configure.deps
-else
-  echo "INSTALL_DIR=$INSTALL_DIR"  >> configure.deps
+if [ $run_cleanup ]; then
+  run_cleanup
+fi
+
+# Extra generator setting (passed in as an argument)
+if [[ -n $ide ]]; then
+  GENERATOR="-G $ide"
+fi
+if [ $no_openmp ]; then
+  NO_OPENMP=true
+fi
+if [ $experimental ]; then
+  EXPERIMENTAL=true
+fi
+if [[ -n $prefix ]]; then
+  INSTALL_DIR=$prefix
+fi  
+
+
+# If not specified we assume gcc and g++ are the default c and c++
+# compilers
+if [[ -z $CC ]]; then
+  CC=gcc
+fi
+if [[ -z $CXX ]]; then
+  CXX=g++
 fi
 
 
+# Test java
+if [[ -z $JAVAC ]]; then
+  JAVAC=javac
+fi
+# set -e
+# set -o pipefail
+
+if ! $JAVAC -version >> /dev/null; then
+  JAVAC="" 
+fi
+
+if [[ -n $no_jvm ]]; then
+  echo "JVM disabled"
+  JAVAC=""
+fi 
+
+## Begin logging in config.log
+LOG_FILE=config.log
+date | tee $LOG_FILE
 
 
-# Run the configure deps
-source configure.deps 
 
 
-#if cmake was not defined then define it
+
+
+
+## ===================================================================
+## Setup CMake
+# Automatically detect and install a sufficiently new version of 
+# cmake
+
+## Install cmake
+if [ `which cmake` ]; then
+  #test cmake version
+  echo "Testing existing cmake version..."
+  currentversion=`cmake --version | tr -dc '[0-9].'`
+  echo "Detected $currentversion . Required 2.8.3"
+  check_version "2.8.3" $currentversion
+  versionok=$?
+  if [ $versionok -eq 1 ]; then
+    echo "CMake version is good"
+    CMAKE="cmake"
+  fi
+fi
+
+# CMake not found and there is a cmake in the deps directory!
+if [ -z $CMAKE ] && [ -f $DEPS_PREFIX/bin/cmake ]; then 
+  #test cmake version
+  echo "Testing existing cmake version..."
+  currentversion=`$DEPS_PREFIX/bin/cmake --version | tr -dc '[0-9].'`
+  echo "Detected $currentversion . Required 2.8.3"
+  check_version "2.8.3" $currentversion
+  versionok=$?
+  if [ $versionok -eq 1 ]; then
+    echo "CMake version is good"
+    CMAKE=$DEPS_PREFIX/bin/cmake
+  fi
+fi
+
 if [ -z $CMAKE ]; then
-    CMAKE=cmake
+  echo "This script will now proceed to download CMake and set it up in"
+  echo "the local graphlabapi/deps directory. The GraphLab compilation "
+  echo "process will be directed to use graphlabapi/deps/cmake."
+  pushd .
+  mkdir deps
+  cd deps
+
+  # get the cmake software page
+  rm -f software.html
+  download_file "http://www.cmake.org/cmake/resources/software.html" software.html
+  # look for the first tar.gz I can download
+  cmakedownload=`grep -m 1 -o -e "href=\"http://www\\.cmake.*\\.tar\\.gz\"" software.html | grep -o -e "http.*\\.tar\\.gz"`
+  if [ -z "$cmakedownload" ] ; then
+    echo "Unable to locate CMake package. You will have to install it yourself."
+    exit 1
+  fi
+  rm -f cmake.tar.gz
+  set -e
+  download_file $cmakedownload cmake.tar.gz
+  tar -xzvf cmake.tar.gz
+  # cd into the extracted directory and install
+  cd cmake-*
+  ./configure --prefix=$DEPS_PREFIX
+  make -j2
+  make install
+  set +e
+  popd 
+  CMAKE=$DEPS_PREFIX/bin/cmake
+  echo "CMAKE=$CMAKE" >> configure.deps
 fi
 
+## ============================================================================
+# Regenerate the configure.deps
+echo -e "# Release build directory:" >> configure.deps
+echo -e "\t RELEASE_DIR=$RELEASE_DIR" >> configure.deps
 
-echo -e \
-    "======================= BUILD CONFIGURATION ========================\n"\
-    "System Information: " | tee -a $LOG_FILE
+echo -e "# Debug build directory (optimization disabled):" >> configure.deps
+echo -e "\t DEBUG_DIR=$DEBUG_DIR" >> configure.deps
+
+echo -e "# Directory in which graphlab is installed (prefix):" >> configure.deps
+echo -e "\t INSTALL_DIR=$INSTALL_DIR" >> configure.deps
+
+echo -e "# Is experimental (research) code enabled:" >> configure.deps
+echo -e "\t EXPERIMENTAL=$EXPERIMENTAL" >> configure.deps
+
+echo -e "# The graphlab home directory: " >> configure.deps
+echo -e "\t GRAPHLAB_HOME=$GRAPHLAB_HOME" >> configure.deps
+
+echo -e "# The directory in which graphlab installs external dependencies:" >> configure.deps
+echo -e "\t DEPS_PREFIX=$DEPS_PREFIX" >> configure.deps
+
+echo -e "# Use OpenMP?  This can accelerate some graph building code: " >> configure.deps
+echo -e "\t NO_OPENMP=$NO_OPENMP" >> configure.deps
+
+echo -e "# The c compiler to use: " >> configure.deps
+echo -e "\t CC=$CC" >> configure.deps
+
+echo -e "# The c++ compiler to use: " >> configure.deps
+echo -e "\t CXX=$CXX" >> configure.deps
+
+echo -e "# Any addition user defined CFLAGS: " >> configure.deps
+echo -e "\t CFLAGS=$CFLAGS" >> configure.deps
+
+echo -e "# The Java compiler: " >> configure.deps
+echo -e "\t JAVAC=$JAVAC" >> configure.deps
+
+echo -e "# The cmake binary used to geneate the project:" >> configure.deps
+echo -e "\t CMAKE=$CMAKE" >> configure.deps
+
+
+echo "======================= BUILD CONFIGURATION ========================"
+echo "System Information: " | tee -a $LOG_FILE
 uname -v | tee -a $LOG_FILE
-echo "GCC Information: " | tee -a $LOG_FILE
-gcc --version | tee -a $LOG_FILE
-g++ --version | tee -a $LOG_FILE
-
-echo -e \
-    "Release build path:        $RELEASE_DIR \n"\
-    "Debug build path:          $DEBUG_DIR \n"\
-    "Profile build path:        $PROFILE_DIR \n"\
-    "Install path:              $INSTALL_DIR \n"\
-    "BOOST_ROOT:                $BOOST_ROOT \n"\
-    "Build experimental parts:  $EXPERIMENTAL \n" | tee -a $LOG_FILE
-
-
-
-
-
-# Construct config flags for cmake
-if [ ! -z $INSTALL_DIR ]; then
-    config_flags="$config_flags -D CMAKE_INSTALL_PREFIX:STRING=$INSTALL_DIR"
+echo "Compiler Information: " | tee -a $LOG_FILE
+$CC --version      | tee -a $LOG_FILE
+$CXX --version     | tee -a $LOG_FILE
+$CMAKE --version   | tee -a $LOG_FILE
+if [[ -n $JAVAC ]]; then
+  $JAVAC -version  | tee -a $LOG_FILE
 fi
 
-if [ ! -z $BOOST_ROOT ]; then
-    config_flags="$config_flags -D BOOST_ROOT:STRING=$BOOST_ROOT"
+echo "======================= Config File ================================"
+
+cat configure.deps | tee -a $LOG_FILE
+
+
+### Add addition config flags =================================================
+CFLAGS="$CFLAGS -D NO_OPENMP:BOOL=$NO_OPENMP"
+CFLAGS="$CFLAGS -D CMAKE_INSTALL_PREFIX:STRING=$INSTALL_DIR"
+CFLAGS="$CFLAGS -D EXPERIMENTAL:BOOL=$EXPERIMENTAL"
+if [ -z $JAVAC ]; then
+  CFLAGS="$CFLAGS -D NO_JAVAC:BOOL=1"
 fi
 
+## ============================================================================
+# Run Cmake
 
-
-
-
-
-if [ ! -z $EXPERIMENTAL ]; then
-    config_flags="$config_flags -D EXPERIMENTAL:BOOL=$EXPERIMENTAL"
-fi
-
-# if [ ! -z $YRL_EXPERIMENTAL ]; then
-#     config_flags="$config_flags -D YRL_EXPERIMENTAL:BOOL=$YRL_EXPERIMENTAL"
-#    if [ ! -z $AVRO_ROOT ]; then
-#        config_flags="$config_flags -D AVRO_ROOT:STRING=$AVRO_ROOT"
-#    fi
-# fi
-
-
-if [ ! -z $itpp_static_link_dir ]; then
-    config_flags="$config_flags -D ITPP_STATIC_LINK_DIR:STRING=$itpp_static_link_dir"
-fi
-if [ ! -z $itpp_dynamic_link_dir ]; then
-    config_flags="$config_flags -D ITPP_DYNAMIC_LINK_DIR:STRING=$itpp_dynamic_link_dir"
-fi
-if [ ! -z $itpp_include_dir ]; then
-   config_flags="$config_flags -D ITPP_INCLUDE_DIR:STRING=$itpp_include_dir"
-fi
-if [ ! -z $itpp_lapack_dir ]; then
-   config_flags="$config_flags -D ITPP_LAPACK_DIR:STRING=$itpp_lapack_dir"
-fi
-
-
-if [ ! -z $HAS_EIGEN ]; then
-   config_flags="$config_flags -D HAS_EIGEN:STRING=true"
-fi
-### CONSTRUCT THE BUILD DIRECTORIES ===========================================
 
 set -e
+set -o pipefail
+
+
 
 echo -e "\n\n\n======================= Release ========================" \
     | tee -a $LOG_FILE 
-
-
 
 if [ ! -d $RELEASE_DIR ]; then
     mkdir $RELEASE_DIR
@@ -254,8 +313,9 @@ fi
 cd $RELEASE_DIR
 rm -f CMakeCache.txt
 build_cmd="$CMAKE \
+    $GENERATOR \
     -D CMAKE_BUILD_TYPE=Release \
-    $config_flags \
+    $CFLAGS \
     ../."
 echo $build_cmd | tee -a "../$LOG_FILE"
 eval $build_cmd | tee -a "../$LOG_FILE"
@@ -271,30 +331,15 @@ fi
 cd $DEBUG_DIR
 rm -f CMakeCache.txt
 build_cmd="$CMAKE \
+    $GENERATOR \
     -D CMAKE_BUILD_TYPE=Debug \
-    $config_flags \
+    $CFLAGS \
     ../."
 echo $build_cmd | tee -a ../$LOG_FILE
 eval $build_cmd | tee -a ../$LOG_FILE
 cd $GRAPHLAB_HOME
 
 
-echo -e "\n\n\n======================= Profile ========================" \
-    | tee -a $LOG_FILE 
 
-if [ ! -d $PROFILE_DIR ]; then
-    mkdir $PROFILE_DIR
-fi
-cd $PROFILE_DIR
-rm -f CMakeCache.txt
-build_cmd="$CMAKE \
-    -D CMAKE_BUILD_TYPE=Release \
-    -D COMPILE_PROFILING=1 \
-    $config_flags \
-    ../."
-
-echo $build_cmd | tee -a ../$LOG_FILE
-eval $build_cmd | tee -a ../$LOG_FILE
-cd $GRAPHLAB_HOME
 
 
